name: Deploy Flask App to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: sodium-ray-489408-m7
  REGION: us-central1
  SERVICE: github-actions
  WORKLOAD_IDENTITY_PROVIDER: projects/341184722174/locations/global/workloadIdentityPools/github-pool/providers/github
  SERVICE_ACCOUNT: github-actions@sodium-ray-489408-m7.iam.gserviceaccount.com

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build Docker Image
        run: |
          docker build -t us-central1-docker.pkg.dev/$PROJECT_ID/cicd-demo/app:$GITHUB_SHA .

      - name: Push Docker Image
        run: |
          docker push us-central1-docker.pkg.dev/$PROJECT_ID/cicd-demo/app:$GITHUB_SHA

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE \
            --image us-central1-docker.pkg.dev/$PROJECT_ID/cicd-demo/app:$GITHUB_SHA \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated